# End your baseURL with a `/` trailing slash, e.g. `https://example.com/`.
baseURL = "https://kiskander.github.io/cisco-learning-codelabs/"

title = "Cisco Learning and Certifications"
languageCode = "en-us"
theme = "codelabs"

[params]
homeTitle = "Welcome to the Launchpad 🚀"
homeDescription = "Launch your free learning resources with a curated list of content and watch your skills skyrocket to the moon!"
footer = "<a href=\"https://cisco.com\" target=\"_new\">©2022 Cisco Systems, Inc.</a>"
feedbackLink = "mailto:donotreply@cisco.com"

[params.categoryColors]
mlops = "#1A73E8"
tfx = "#f58442"
gcp = "#3884ff"
jupyter = "#fc4903"
mtest = "#1A73E8"
server = "#000000"
